import { contextBridge, ipcRenderer } from 'electron'
import { electronAPI } from '@electron-toolkit/preload'

const api = {
  loadData: () => ipcRenderer.invoke('load-data'),
  saveData: (data) => ipcRenderer.invoke('save-data', data),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  openFolder: (path) => ipcRenderer.invoke('open-folder', path),
  fetchFabricVersions: () => ipcRenderer.invoke('fetch-fabric-versions'),
  installFabric: (opts) => ipcRenderer.invoke('install-fabric', opts),
  startServer: (opts) => ipcRenderer.invoke('start-server', opts),
  stopServer: (opts) => ipcRenderer.invoke('stop-server', opts),
  sendCommand: (opts) => ipcRenderer.invoke('send-command', opts),
  fetchGlobalIp: () => ipcRenderer.invoke('fetch-global-ip'),
  onInstallLog: (cb) => ipcRenderer.on('install-log', (_, msg) => cb(msg)),
  onServerLog: (serverId, cb) => ipcRenderer.on(`log-${serverId}`, (_, msg) => cb(msg)),
  onServerStopped: (serverId, cb) => ipcRenderer.on(`stopped-${serverId}`, () => cb()),
  removeAllListeners: (channel) => ipcRenderer.removeAllListeners(channel),
  deleteServerDir: (opts) => ipcRenderer.invoke('delete-server-dir', opts),
  createClusterDir: (opts) => ipcRenderer.invoke('create-cluster-dir', opts),
  installVelocity: (opts) => ipcRenderer.invoke('install-velocity', opts),
  onVelocityLog: (cb) => ipcRenderer.on('velocity-log', (_, msg) => cb(msg)),
  startVelocity: (opts) => ipcRenderer.invoke('start-velocity', opts),
  stopVelocity: (opts) => ipcRenderer.invoke('stop-velocity', opts),
  onVelocityStarted: (clusterId, cb) => ipcRenderer.on(`velocity-started-${clusterId}`, () => cb()),
  onVelocityStopped: (clusterId, cb) => ipcRenderer.on(`velocity-stopped-${clusterId}`, () => cb()),
  onVelocityRunLog: (clusterId, cb) => ipcRenderer.on(`velocity-log-${clusterId}`, (_, msg) => cb(msg)),
  onServerStarted: (serverId, cb) => ipcRenderer.on(`started-${serverId}`, () => cb()),
  readServerProperties: (opts) => ipcRenderer.invoke('read-server-properties', opts),
  writeServerProperties: (opts) => ipcRenderer.invoke('write-server-properties', opts),
  writeVelocityToml: (opts) => ipcRenderer.invoke('write-velocity-toml', opts),
  setupFabricProxy: (opts) => ipcRenderer.invoke('setup-fabric-proxy', opts),
  scanClusterDir: (opts) => ipcRenderer.invoke('scan-cluster-dir', opts),
  scanServerDir: (opts) => ipcRenderer.invoke('scan-server-dir', opts),
  fetchPaperVersions: () => ipcRenderer.invoke('fetch-paper-versions'),
  installPaper: (opts) => ipcRenderer.invoke('install-paper', opts),
  setupPaperProxy: (opts) => ipcRenderer.invoke('setup-paper-proxy', opts),
  getLibraryStructure: (opts) => ipcRenderer.invoke('get-library-structure', opts),
  addLibraryItem: (opts) => ipcRenderer.invoke('add-library-item', opts),
  removeLibraryItem: (opts) => ipcRenderer.invoke('remove-library-item', opts),
  addModSource: (opts) => ipcRenderer.invoke('add-mod-source', opts),
  removeModSource: (opts) => ipcRenderer.invoke('remove-mod-source', opts),
  checkPort: (opts) => ipcRenderer.invoke('check-port', opts),
  addPaperPluginSource: (opts) => ipcRenderer.invoke('add-paper-plugin-source', opts),
  removePaperPluginSource: (opts) => ipcRenderer.invoke('remove-paper-plugin-source', opts),
  addVelocityPluginSource: (opts) => ipcRenderer.invoke('add-velocity-plugin-source', opts),
  removeVelocityPluginSource: (opts) => ipcRenderer.invoke('remove-velocity-plugin-source', opts),
  applyServerMods: (opts) => ipcRenderer.invoke('apply-server-mods', opts),
  applyServerPlugins: (opts) => ipcRenderer.invoke('apply-server-plugins', opts),
  selectFile: () => ipcRenderer.invoke('select-file'),
  watchLibrary: (opts) => ipcRenderer.invoke('watch-library', opts),
  unwatchLibrary: () => ipcRenderer.invoke('unwatch-library'),
  onLibraryChanged: (cb) => ipcRenderer.on('library-changed', () => cb()),
  copyServerProfile: (opts) => ipcRenderer.invoke('copy-server-profile', opts),
  deleteWorldData: (opts) => ipcRenderer.invoke('delete-world-data', opts),
  backupServer: (opts) => ipcRenderer.invoke('backup-server', opts),
  onServerRestarting: (serverId, cb) => ipcRenderer.on(`restarting-${serverId}`, () => cb()),
  modrinthSearch: (opts) => ipcRenderer.invoke('modrinth-search', opts),
  modrinthVersions: (opts) => ipcRenderer.invoke('modrinth-versions', opts),
  modrinthDownload: (opts) => ipcRenderer.invoke('modrinth-download', opts),
  modrinthResolveFiles: (opts) => ipcRenderer.invoke('modrinth-resolve-files', opts),
  onModrinthDownloadProgress: (cb) => ipcRenderer.on('modrinth-download-progress', (_, info) => cb(info)),
  detectJava: () => ipcRenderer.invoke('detect-java'),
  validateJavaPath: (opts) => ipcRenderer.invoke('validate-java-path', opts),
  installJava: (opts) => ipcRenderer.invoke('install-java', opts),
  onJavaInstallLog: (cb) => ipcRenderer.on('java-install-log', (_, msg) => cb(msg)),
  onJavaInstallProgress: (cb) => ipcRenderer.on('java-install-progress', (_, info) => cb(info)),
  onJavaInstallDone: (cb) => ipcRenderer.on('java-install-done', (_, info) => cb(info)),
  getOps: (opts) => ipcRenderer.invoke('get-ops', opts),
  setOps: (opts) => ipcRenderer.invoke('set-ops', opts),
  fetchUuid: (opts) => ipcRenderer.invoke('fetch-uuid', opts),
  listModConfigs: (opts) => ipcRenderer.invoke('list-mod-configs', opts),
  readConfigFile: (opts) => ipcRenderer.invoke('read-config-file', opts),
  writeConfigFile: (opts) => ipcRenderer.invoke('write-config-file', opts),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_, info) => cb(info)),
  onUpdateDownloadProgress: (cb) => ipcRenderer.on('update-download-progress', (_, info) => cb(info)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (_, info) => cb(info)),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_, info) => cb(info)),
  installUpdate: () => ipcRenderer.invoke('install-update'),
}

if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI)
    contextBridge.exposeInMainWorld('api', api)
  } catch (error) {
    console.error(error)
  }
} else {
  window.electron = electronAPI
  window.api = api
}